// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawyu93N7vJXd9GwIuY_lvrvhbVgvs9AE',
    appId: '1:103686844490:web:f19fdd2656ad9a941b36b3',
    messagingSenderId: '103686844490',
    projectId: 'whatsapp-clone-backend-60316',
    authDomain: 'whatsapp-clone-backend-60316.firebaseapp.com',
    storageBucket: 'whatsapp-clone-backend-60316.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsn28H1hR413FA7FvQ5-EBJ9xWQcRjj2g',
    appId: '1:103686844490:android:719a15c1c4d9181e1b36b3',
    messagingSenderId: '103686844490',
    projectId: 'whatsapp-clone-backend-60316',
    storageBucket: 'whatsapp-clone-backend-60316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB272yozIUK6uJTj_W_yUzxhaMPi0v5zSo',
    appId: '1:103686844490:ios:4c6e125cdaeba2641b36b3',
    messagingSenderId: '103686844490',
    projectId: 'whatsapp-clone-backend-60316',
    storageBucket: 'whatsapp-clone-backend-60316.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
